Pr for Json pimp
Teaching-projects/SZE-MOSZE-2020-TheThreeVision pull request #12
Opened 2020-11-12 19:40 UTC by borbelytomii

Elkészült a JSON pimp

2020-11-14 16:08 UTC, AlmasiSzabolcs requested changes
Részemről jó, még a dokumentációt kellene aktualizálni.

2020-11-16 16:10 UTC, kristofelo approved these changes

2020-11-16 16:10 UTC, kristofelo commented on JSON.cpp
> +        } while (isdigit(StringToParse[findWord]) or isalpha(StringToParse[findWord]) or StringToParse[findWord] == ' ' or StringToParse[findWord] == '.' or StringToParse[findWord] == '_' or StringTo
Itt lehetne szépíteni, de amúgy rendben van.

2020-11-16 18:42 UTC, poloczmate approved these changes

2020-11-16 18:42 UTC, merged