PR for Second-Work
Teaching-projects/SZE-MOSZE-2020-TheThreeVision pull request #2
Opened 2020-09-24 19:20 UTC by radvanszkyI

Második feladat teljesítve: 
-tesztek elkészítése,
-parseUnit létrehozása.

2020-09-26 13:17 UTC, hegyhati requested changes
Elkezdtem nezni, bennehagytam par commente, aztan feltunt, hgoy a teljes player, stb uj. Nem rebase-eltetek masterre/nem jo helyen nyitottatok. Ezt nagyon gyorsan csinaljatok meg, addig nem nezek ra, amig ez nincs rendben.

2020-09-26 13:17 UTC, hegyhati commented on main.cpp
> +    Player* Player2 = Player::parseUnit(argv[2]);
miert a heap-en csinaljatok?

2020-09-26 13:17 UTC, hegyhati commented on main.cpp
> +    Player* Player2 = Player::parseUnit(argv[2]);
Hol van lekezelve, hogy nincsen ilyen fajl, vagy ennyi argumentum?

2020-09-26 13:17 UTC, hegyhati commented on main.cpp
> +	cin.get();
ilyet ne lassk. tanuljatok meg hasznalni a fejlesztokornyezeteteket, ne a kodba szemeteljetek emiatt.

2020-09-26 13:17 UTC, hegyhati commented on main.cpp
> +}
return?!

2020-09-26 13:17 UTC, hegyhati commented on README.md
> +Készítette: Borbély Tamás, Polócz Máté, Radvánszky István
Ennel azert lehetne kicsit bovebb is.

2020-09-26 18:48 UTC, radvanszkyI commented
@hegyhati megcsináltuk a kért módosításokat.
Azért a heapon hoztuk létre az objektumokat (a main-ban), mert a const attribútumoknak így adtunk a parseUnitból megfelelő kezdeti értéket.

2020-10-01 11:23 UTC, radvanszkyI commented
@hegyhati megcsináltuk a kért módosításokat.

2020-10-01 16:32 UTC, hegyhati requested changes

2020-10-01 16:32 UTC, hegyhati commented on main.cpp
> +        Player* Player2 = Player::parseUnit(argv[2]);
Hat azert a main-ben ne throw-oljunk, meg itt nincs elkapva ha a parzolas nem jon ossze.

2020-10-02 14:05 UTC, radvanszkyI commented on main.cpp
> +        Player* Player2 = Player::parseUnit(argv[2]);
@hegyhati javítva

2020-10-03 10:50 UTC, hegyhati approved these changes

2020-10-03 10:51 UTC, merged