Levelup
Teaching-projects/SZE-MOSZE-2020-TheThreeVision pull request #4
Opened 2020-10-12 13:30 UTC by borbelytomii

3. feladat 2.része elkészült. :  Levelup branch elkészítve GHA workflowval

2020-10-13 12:09 UTC, oliverosz requested changes
Pár apróságot leszámítva rendben van.

2020-10-13 12:09 UTC, oliverosz commented on player.cpp
> +			this->levelup(this->getXP() / 100);
Ez így nem "minden elért 100 xp után" lép egy szintet, hanem "legalább a következő 100-as xp elérése után" lép **pontosan 1 szintet**. Egy ütésből most nem tud több szintet lépni. A `levelup` paramétere meg nincs használva.

2020-10-13 12:09 UTC, oliverosz commented on player.cpp
> +			if (othXP / 100 < otherplayer->getXP() / 100)//minden el�rt 100 xp ut�n
Szintén. (Ugye emiatt kerüljük a kódismétlést, hogy csak 1 helyen kelljen javítani.)

2020-10-13 12:09 UTC, oliverosz commented on player.h
> +	void setHP(int h) { HP = h; }
Ez legyen protected.

2020-10-13 12:09 UTC, oliverosz commented on player.h
> +	void setDMG(int d) { DMG = d; }
protected

2020-10-13 12:09 UTC, oliverosz commented on player.h
> +	void levelup(int levelnew);
protected

2020-10-13 12:09 UTC, oliverosz commented on player.h
> +	void increaseXP(int dmg);
protected

2020-10-13 12:09 UTC, oliverosz commented on player.h
> +#include <cmath>
A `cmath` csak a cpp-ben kell, itt nincs használva.

2020-10-14 10:27 UTC, borbelytomii commented on player.h
> +	void setDMG(int d) { DMG = d; }
getHP használva van a main.cpp-ben, mert az elvárt kimenet tartalmazza a megmaradt HP-t.

2020-10-14 15:03 UTC, borbelytomii commented
@oliverosz Módosításokat elvégeztem.

2020-10-15 13:32 UTC, oliverosz approved these changes
Rendben van, ha @hegyhati ad jogosultságot, be is mergelem.

2020-10-15 13:39 UTC, hegyhati commented
> Rendben van, ha @hegyhati ad jogosultságot, be is mergelem.

szerintem van mar.

2020-10-15 14:41 UTC, merged