Unittests finished
Teaching-projects/SZE-MOSZE-2020-TheThreeVision pull request #7
Opened 2020-10-29 12:08 UTC by borbelytomii

Elkészült a 4. feladat Unittest része.

2020-10-30 10:20 UTC, AlmasiSzabolcs requested changes
Pár módosítás után elfogadható lesz.

2020-10-30 10:20 UTC, AlmasiSzabolcs commented on test/unit_test.cpp
> +TEST(Finddatatest, atkcd)
A gtestek közül a Nametest, dmgtest,atkcd, Hptest szebben mutatna 1 gtestként.

2020-10-30 10:20 UTC, AlmasiSzabolcs commented on test/unit_test.cpp
> +}
Ez a gtest ugyanaz, mint az 58. sorban kezdődő TestingWithFilenameInput_randomkeys test, nem?

2020-10-30 10:20 UTC, AlmasiSzabolcs commented on .github/workflows/jsonparser.yml
> +      - gh-pages
gh-pagesen nincs c++ kód amiből  generálódjon, nem?

2020-10-31 09:17 UTC, borbelytomii commented on test/unit_test.cpp
> +}
Nem ugyanaz , mivel az előző TestingWithFilenameInput_randomkeys az más sorrendben teszteli a kulcsokat.

2020-10-31 09:18 UTC, borbelytomii commented on .github/workflows/jsonparser.yml
> +      - gh-pages
Köszi az észrevételt, már másik branchről megoldva a probléma. (Outdated)

2020-10-31 09:30 UTC, borbelytomii commented on test/unit_test.cpp
> +TEST(Finddatatest, atkcd)
Köszi, javítva!

2020-10-31 10:08 UTC, AlmasiSzabolcs commented on test/unit_test.cpp
> +}
Szóról szóra ugyanaz! Az inputFilename-ben tárolt stringet nézd meg, mindkét gtestben a unit2.json-t kapja. Nem lehet, hogy az egyik gtest a unit.json-re van írva? :)

2020-10-31 10:16 UTC, AlmasiSzabolcs requested changes

2020-10-31 10:16 UTC, AlmasiSzabolcs commented on test/unit_test.cpp
>  	std::string inputString = "{\n\t\"name\":\"vizibicikli\",\n\t\"dmg\":1450,\n\t\"hp\":15330,\n\"atkcd\":2}";
Miért van az inputString előtt a toFind és az expected string?

2020-11-01 15:20 UTC, borbelytomii commented on test/unit_test.cpp
> +}
Köszi az észrevételt , igazad van elírás történt.

2020-11-01 16:21 UTC, borbelytomii commented on test/unit_test.cpp
>  	std::string inputString = "{\n\t\"name\":\"vizibicikli\",\n\t\"dmg\":1450,\n\t\"hp\":15330,\n\"atkcd\":2}";
Köszi az észrevételt, javítva.

2020-11-01 18:47 UTC, AlmasiSzabolcs approved these changes

2020-11-01 18:48 UTC, kristofelo approved these changes

2020-11-03 10:55 UTC, poloczmate approved these changes

2020-11-03 10:55 UTC, merged