Makefile finished
Teaching-projects/SZE-MOSZE-2020-TheThreeVision pull request #9
Opened 2020-10-31 15:13 UTC by radvanszkyI

2020-10-31 19:44 UTC, hegyhati requested changes

2020-10-31 19:44 UTC, hegyhati commented on Makefile
> +main.o: main.cpp player.h
ha aplayernek kellett a parser, akkor itt miert nem?

2020-11-02 12:05 UTC, radvanszkyI commented on Makefile
> +main.o: main.cpp player.h
@hegyhati megcsináltam a kért módosítást

2020-11-03 09:32 UTC, hegyhati approved these changes

2020-11-03 09:33 UTC, merged